apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-server
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kv-server
  template:
    metadata:
      labels:
        app: kv-server
    spec:
      containers:
      - name: kv-server
        image: localhost:5000/kv-server:latest
        ports:
        - name: tcp-port
          containerPort: 8080
          protocol: TCP
        - name: epmd-port
          containerPort: 4369
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: kv-server-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: kv-server
  ports:
  - name: server-port
    port: 8080
    targetPort: tcp-port
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kv-server-nodes
  namespace: default
spec:
  clusterIP: None
  selector:
    app: kv-server
  ports:
  # This port is not effectively used! 
  # This is just a way of exposing the pod internal ips through the service
  - name: epmd
    port: 4369
    targetPort: epmd-port
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kv-server-ingress
spec:
  rules:
  - host: kv-server.k8s.kind
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: kv-service-lb
            port: 
              number: 8080

